[project]
name = "jumpstarter-driver-tasmota"
dynamic = ["version", "urls"]
description = "Jumpstarter driver for controlling Tasmota-compatible devices via MQTT"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "Nick Cao", email = "nickcao@nichi.co" }]
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter_driver_power",
    "jumpstarter",
    "paho-mqtt>=2.1.0",
]

[project.entry-points."jumpstarter.drivers"]
TasmotaPower = "jumpstarter_driver_tasmota.driver:TasmotaPower"


[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_tasmota"]

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pytest-mqtt>=0.5.0",
]
