[project]
name = "jumpstarter-all"
dynamic = ["version", "urls"]
description = "Jumpstarter meta-package which will install all packages"
authors = [{ name = "Miguel Angel Ajo", email = "majopela@redhat.com" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
  "jumpstarter",
  "jumpstarter-cli",
  "jumpstarter-cli-admin",
  "jumpstarter-cli-common",
  "jumpstarter-cli-driver",
  "jumpstarter-driver-can",
  "jumpstarter-driver-composite",
  "jumpstarter-driver-corellium",
  "jumpstarter-driver-dutlink",
  "jumpstarter-driver-flashers",
  "jumpstarter-driver-http",
  "jumpstarter-driver-network",
  "jumpstarter-driver-opendal",
  "jumpstarter-driver-power",
  "jumpstarter-driver-probe-rs",
  "jumpstarter-driver-pyserial",
  "jumpstarter-driver-qemu",
  "jumpstarter-driver-gpiod",
  "jumpstarter-driver-ridesx",
  "jumpstarter-driver-sdwire",
  "jumpstarter-driver-shell",
  "jumpstarter-driver-snmp",
  "jumpstarter-driver-tftp",
  "jumpstarter-driver-uboot",
  "jumpstarter-driver-ustreamer",
  "jumpstarter-driver-yepkit",
  "jumpstarter-imagehash",
  "jumpstarter-kubernetes",
  "jumpstarter-protocol",
  "jumpstarter-testing",
]

[tool.hatch.build.targets.wheel]
packages = ["jumpstarter_all"]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"
