[project]
name = "jumpstarter-driver-ble"
dynamic = ["version", "urls"]
description = "Bluetooth Low Energy (BLE) driver"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "Andreas Karner", email = "andreas.karner@outlook.com" }]
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter",
    "bleak>=1.1.1",
]

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_ble"]

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pytest-cov>=6.0.0", "pytest>=8.3.3"]

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"
