[project]
name = "jumpstarter-driver-noyito-relay"
dynamic = ["version", "urls"]
description = "Jumpstarter driver for the NOYITO 5V 2-Channel USB Relay Module"
readme = "README.md"
license = "Apache-2.0"
authors = [
    { name = "Kirk Brauer", email = "kbrauer@hatci.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pyserial>=3.5",
    "hid>=1.0.4",
    "jumpstarter",
    "jumpstarter-driver-power",
]

[project.entry-points."jumpstarter.drivers"]
NoyitoPowerSerial = "jumpstarter_driver_noyito_relay.driver:NoyitoPowerSerial"
NoyitoPowerHID = "jumpstarter_driver_noyito_relay.driver:NoyitoPowerHID"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../../'}

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_noyito_relay"]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pytest-mock>=3.14.0",
]
