[project]
name = "jumpstarter-driver-composite"
dynamic = ["version", "urls"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = ["jumpstarter", "click>=8.1.7.2"]

[project.entry-points."jumpstarter.drivers"]
Composite = "jumpstarter_driver_composite.driver:Composite"
Proxy = "jumpstarter_driver_composite.driver:Proxy"

[dependency-groups]
dev = ["pytest>=8.3.2", "pytest-cov>=5.0.0", "jumpstarter-driver-power"]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../../' }

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"
