[project]
name = "jumpstarter-driver-vnc"
dynamic = ["version", "urls"]
description = "Jumpstarter driver for VNC"
readme = "README.md"
license = "Apache-2.0"
authors = [
    { name = "Albert Esteve", email = "aesteve@redhat.com" }
]
requires-python = ">=3.11"
dependencies = [
    "anyio>=4.10.0",
    "jumpstarter",
    "jumpstarter-driver-composite",
    "jumpstarter-driver-network",
    "click",
]

[project.entry-points."jumpstarter.drivers"]
vnc = "jumpstarter_driver_vnc.driver:Vnc"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../../'}

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/jumpstarter/archive/{commit_hash}.zip"

[tool.pytest.ini_options]
addopts = "--cov --cov-report=html --cov-report=xml"
log_cli = true
log_cli_level = "INFO"
testpaths = ["jumpstarter_driver_vnc"]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"

[dependency-groups]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
]
