apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: jumpstarter-router
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: controller-manager
  namespace: {{ default .Release.Namespace .Values.namespace }}
