[project]
name = "jumpstarter-cli-common"
dynamic = ["version", "urls"]
description = ""
authors = [{ name = "Kirk Brauer", email = "kbrauer@hatci.com" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
  "jumpstarter",
  "pydantic>=2.8.2",
  "asyncclick>=8.1.7.2",
  "authlib>=1.4.1",
  "truststore>=0.10.1",
  "joserfc>=1.0.3",
  "yarl>=1.18.3",
]

[dependency-groups]
dev = [
  "pytest>=8.3.2",
  "pytest-anyio>=0.0.0",
  "pytest-asyncio>=0.0.0",
  "pytest-cov>=5.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["jumpstarter_cli_common"]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
