https:
  enabled: true
config:
  issuer: https://dex.dex.svc.cluster.local:5556
  web:
    tlsCert: /etc/dex/tls/tls.crt
    tlsKey: /etc/dex/tls/tls.key
  storage:
    type: kubernetes
    config:
      inCluster: true
  staticClients:
    - id: jumpstarter-cli
      name: Jumpstarter CLI
      public: true
  oauth2:
    responseTypes: ["code", "token", "id_token", "id_token token"]
    passwordConnector: local
  enablePasswordDB: true
  staticPasswords:
    - email: "test-client-oidc@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
      username: "test-client-oidc"
      userID: "73bca0b9-9be6-4e73-a8fb-347c2ac23255"
    - email: "test-client-oidc-provisioning@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
      username: "test-client-oidc-provisioning"
      userID: "464d9494-5cc3-44e1-a380-c0403bd31fcb"
    - email: "test-exporter-oidc@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
      username: "test-exporter-oidc"
      userID: "a4cb4de2-4467-4e5c-a42a-33be8783649d"
    - email: "test-client-hooks@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
      username: "test-client-hooks"
      userID: "b5dc5e3f-5578-5f6d-b53b-44cf9894760e"
    - email: "test-exporter-hooks@example.com"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
      username: "test-exporter-hooks"
      userID: "c6ed6f40-6689-6a7e-c64c-55d0a9a5871f"
  connectors:
    - name: kubernetes
      type: oidc
      id: kubernetes
      config:
        # kubectl get --raw /.well-known/openid-configuration | jq -r '.issuer'
        issuer: "https://kubernetes.default.svc.cluster.local"
        rootCAs:
          - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        userNameKey: sub
        scopes:
          - profile
volumes:
  - name: tls
    secret:
      secretName: dex-tls
volumeMounts:
  - name: tls
    mountPath: /etc/dex/tls
service:
  type: NodePort
  ports:
    http:
      port: 5554
    https:
      port: 5556
      nodePort: 32000
