[project]
name = "jumpstarter-kubernetes"
dynamic = ["version", "urls"]
description = ""
authors = [{ name = "Kirk Brauer", email = "kbrauer@hatci.com" }]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.11"
dependencies = [
  "jumpstarter",
  "pydantic>=2.8.2",
  "kubernetes>=31.0.0",
  "kubernetes-asyncio>=31.1.0",
  "aiohttp>=3.11.18",
  "semver~=2.13",
  "packaging>=25.0",
]

[dependency-groups]
dev = [
  "pytest>=8.3.2",
  "pytest-anyio>=0.0.0",
  "pytest-asyncio>=0.0.0",
  "pytest-cov>=5.0.0",
]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../' }

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-pin-jumpstarter"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"
