{{ range $k, $v := .Values.grpc.additionalRouters }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-router-{{ $k }}
    app.kubernetes.io/name: jumpstarter-controller
  name: jumpstarter-router-grpc-{{ $k }}
  namespace: {{ default $.Release.Namespace $.Values.namespace }}
spec:
  {{ if .Values.grpc.nodeport.enabled }}
  type: NodePort
  {{ end }}

  ports:
  - name: grpc
    port: 8083
    protocol: TCP
    targetPort: 8083
    appProtocol: h2c # HTTP/2 over cleartext for gRPC (fixes edge termination in ingress/router)
    {{ if .Values.grpc.nodeport.enabled }}
    nodePort: {{ .Values.grpc.nodeport.routerPort }}
    {{ end }}
  selector:
    control-plane: controller-router-{{ $k }}
{{ end }}
