apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: jumpstarter-controller
  name: jumpstarter-router-grpc
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  {{ if .Values.grpc.nodeport.enabled }}
  type: NodePort
  {{ end }}

  ports:
  - name: grpc
    port: 8083
    protocol: TCP
    targetPort: 8083
    {{ if .Values.grpc.nodeport.enabled }}
    nodePort: {{ .Values.grpc.nodeport.routerPort }}
    {{ end }}
  selector:
    control-plane: controller-manager
