{{ if eq .Values.grpc.mode "route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    external-exposed: "true"
    shard: external
  name: jumpstarter-router-route
  namespace: {{ default .Release.Namespace .Values.namespace }}
spec:
  {{ if .Values.grpc.routerHostname }}
  host: {{ .Values.grpc.routerHostname }}
  {{ else }}
  host: router.{{ .Values.global.baseDomain | required "a global.baseDomain or a grpc.routerHostname must be provided"}}
  {{ end }}
  port:
    targetPort: 8083
  tls:
    {{ if eq .Values.grpc.tls.mode "passthrough" }}
    termination: passthrough
    {{ end }}
    {{ if eq .Values.grpc.tls.mode "reencrypt" }}
    termination: reencrypt
    {{ end }}
    insecureEdgeTerminationPolicy: None
    {{ if .Values.grpc.tls.routerCertSecret }}
    externalCertificate:
      name: {{ .Values.grpc.tls.routerCertSecret }}
    {{ end }}

  to:
    kind: Service
    name: jumpstarter-router-grpc
    weight: 100
  wildcardPolicy: None
{{ end }}