{{- $namespace := default .Release.Namespace .Values.namespace }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: jumpstarter-controller
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
  name: jumpstarter-secrets
  namespace: {{ $namespace }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      name: jumpstarter-secrets
    spec:
      serviceAccountName: controller-manager
      containers:
        - name: jumpstarter-secrets
          image: quay.io/jumpstarter-dev/jumpstarter-utils:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              {{- range $name := tuple "jumpstarter-router-secret" "jumpstarter-controller-secret" }}
              if ! kubectl get secret {{ $name }} -n {{ $namespace }} >/dev/null 2>&1; then
                kubectl create secret generic {{ $name }} -n={{ $namespace }} \
                  --from-literal=key="$(openssl rand -hex 32)"
              fi
              {{- end }}
      restartPolicy: Never
