[project]
name = "jumpstarter-driver-can"
dynamic = ["version", "urls"]
description = ""
authors = [
  { name = "Miguel Angel Ajo Pelayo", email = "majopela@redhat.com" },
  { name = "Nick Cao", email = "ncao@redhat.com" },
  { name = "Kirk Brauer", email = "kbrauer@hatci.com" },
]
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.11"
dependencies = [
    "jumpstarter",
    "python-can>=4.5.0",
    "can-isotp>=2.0.6",
]

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-cov>=5.0.0",
]

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"
raw-options = { 'root' = '../../'}

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
