name: Kind based CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'controller/**'

jobs:
  deploy-kind:
    strategy:
      matrix:
        method:
          - helm
          - operator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run make deploy (${{ matrix.method }})
        working-directory: controller
        run: make deploy
        env:
          METHOD: ${{ matrix.method }}

  e2e-test-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run operator e2e test
        working-directory: controller
        run: make test-operator-e2e
