name: Kind based CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release-*'
    paths:
      - 'controller/**'

jobs:
  deploy-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run make deploy
        working-directory: controller
        run: make deploy

  e2e-test-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run operator e2e test
        working-directory: controller
        run: make test-operator-e2e
