name: Controller Unit/Functional tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'release-*'
    paths:
      - 'controller/**'
      - 'protocol/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run controller tests
        working-directory: controller
        run: make test

      - name: Cache operator bin directory
        uses: actions/cache@v4
        with:
          path: controller/deploy/operator/bin/
          key: ${{ runner.os }}-operator-bin-${{ hashFiles('controller/deploy/operator/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-operator-bin-

      - name: Run operator tests
        run: make -C controller/deploy/operator test
