name: PR Analytics

on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
      report_date_end:
        description: "Report date end(d/MM/yyyy)"

jobs:
  create-report:
    name: Create report
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Run script for analytics
        uses: AlexSim93/pull-request-analytics-action@2393847d9ed95dbecf321a527f7402aeb3012040 # v4.10.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_FOR_ISSUE: jumpstarter
          GITHUB_OWNER_FOR_ISSUE: jumpstarter-dev
          GITHUB_OWNERS_REPOS: jumpstarter-dev/jumpstarter
          USE_CHARTS: true
          TIMEZONE: "Etc/UTC"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
