name: Trigger Packages Index Generation

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "*"

jobs:
  trigger-packages-index:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'jumpstarter-dev' }}
    steps:
      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.JUMPSTARTER_BACKPORT_BOT_APP_ID }}
          private-key: ${{ secrets.JUMPSTARTER_BACKPORT_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            packages

      - name: Trigger packages repository index generation
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: jumpstarter-dev/packages
          event-type: generate-index
